"use client"

import { useState } from "react"
import { Modal } from "@/components/ui/Modal"
import { useCreateTracker } from "@/hooks/useApi"
import type { ChainKey } from "@/types"

export function AddTrackerModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [form, setForm] = useState({ name: "", walletAddress: "", xUsername: "", chain: "base" as ChainKey, notificationsEnabled: true, minimumTransactionValue: "250" })
  const mutation = useCreateTracker()
  function setField(field: string, value: string | boolean) { setForm((current) => ({ ...current, [field]: value })) }
  async function submit(event: React.FormEvent) { event.preventDefault(); await mutation.mutateAsync(form); setForm({ name: "", walletAddress: "", xUsername: "", chain: "base", notificationsEnabled: true, minimumTransactionValue: "250" }); onClose() }
  return <Modal open={open} onClose={onClose} title="Add tracker" description="Monitor a wallet or X account across the selected chain."><form onSubmit={submit} className="space-y-3"><label className="block"><span className="mb-1.5 block text-xs text-[var(--muted)]">Tracker name</span><input className="input-shell w-full" value={form.name} onChange={(event) => setField("name", event.target.value)} placeholder="Smart Money" required maxLength={50} /></label><label className="block"><span className="mb-1.5 block text-xs text-[var(--muted)]">Wallet address</span><input className="input-shell w-full font-mono text-xs" value={form.walletAddress} onChange={(event) => setField("walletAddress", event.target.value)} placeholder="0x..." /></label><label className="block"><span className="mb-1.5 block text-xs text-[var(--muted)]">X username</span><input className="input-shell w-full" value={form.xUsername} onChange={(event) => setField("xUsername", event.target.value)} placeholder="@username" /></label><div className="grid grid-cols-2 gap-3"><label className="block"><span className="mb-1.5 block text-xs text-[var(--muted)]">Chain</span><select className="input-shell w-full" value={form.chain} onChange={(event) => setField("chain", event.target.value)}><option value="base">Base</option><option value="robinhood">Robinhood</option></select></label><label className="block"><span className="mb-1.5 block text-xs text-[var(--muted)]">Min. tx value</span><input className="input-shell w-full" value={form.minimumTransactionValue} onChange={(event) => setField("minimumTransactionValue", event.target.value)} inputMode="decimal" /></label></div><label className="flex items-center gap-2 py-2 text-xs text-[var(--muted)]"><input type="checkbox" checked={form.notificationsEnabled} onChange={(event) => setField("notificationsEnabled", event.target.checked)} className="accent-accent" /> Notify me about new activity</label>{mutation.error && <p className="text-xs text-red-300">{mutation.error.message}</p>}<button className="primary-button w-full" disabled={mutation.isPending}>{mutation.isPending ? "Creating..." : "Create tracker"}</button></form></Modal>
}
